node:
  image: node:4.1.2
  volumes:
    - .:/app
  working_dir: /app

npm:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    http_proxy: ${http_proxy}
  entrypoint: ['npm']

devserver:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    server_url: http://localhost:3000/ebsco
  ports:
    - 3001:3001
  command: node node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.dev.js --port 3001 --host 0.0.0.0

build:
  extends:
    file: ./docker-compose.yml
    service: node
  command: node node_modules/webpack/bin/webpack.js --config webpack.config.prod.js -p

test:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    NODE_ENV: test
  command: node_modules/mocha/bin/mocha test/mocha test/mocha/**/*.js
