'use strict';

import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import actions from '../actions';

import SelectLimiter from '../components/SelectLimiter';

const languages = [
    'Afrikaans',
    'Arabic',
    'Bosnian',
    'Chinese',
    'Croatian',
    'Czech',
    'English',
    'Dutch/Flemish',
    'French',
    'German',
    'Italian',
    'Japanese',
    'Lithuanian',
    'Norwegian',
    'Polish',
    'Portuguese',
    'Russian',
    'Serbian',
    'Slovak',
    'Slovenian',
    'Turkish',
    'Khmer',
    'Korean',
    'Mongolian',
    'Persian',
    'Sanskrit',
    'Swedish',
    'Thai',
    'Tibetan',
    'Vietnamese',
    'Dutch',
    'Greek, Modern',
    'Hebrew',
    'Indonesian',
    'Latin',
    'Aragonese',
    'Breton',
    'Catalan; Valencian',
    'Danish',
    'Dutch; Flemish',
    'Galician',
    'Hungarian',
    'Slavic languages',
    'Spanish; Castilian',
    'Greek, Ancient',
    'Occitan',
    'Welsh',
    'Undefined',
    'Gaelic; Scottish Gaelic',
    'Albanian',
    'Armenian',
    'Azerbaijani',
    'Bulgarian',
    'Catalan',
    'Finnish',
    'Georgian',
    'Greek',
    'Icelandic',
    'Macedonian',
    'Swahili',
    'Hindi',
    'Latvian',
    'Malay',
    'Urdu',
    'Basa',
    'Belarusian',
    'Chinook jargon',
    'English, Middle (1100-1500)',
    'Estonian',
    'Ewe',
    'Greek, Modern (1453-)',
    'Hmong; Mong',
    'Hiri Motu',
    'Javanese',
    'Kannada',
    'Malayalam',
    'Maori',
    'Marathi',
    'Multiple languages',
    'North American Indian languages',
    'Nepali',
    'Ojibwa',
    'Romanian; Moldavian; Moldovan',
    'Somali',
    'Tamil',
    'Undetermined',
    'Yiddish',
    'Achinese',
    'Amharic',
    'English, Old (ca.450-1100)',
    'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)',
    'Assamese',
    'Avestan',
    'Awadhi',
    'Bashkir',
    'Baluchi',
    'Balinese',
    'Bengali',
    'Berber languages',
    'Bhojpuri',
    'Bantu languages',
    'Braj',
    'Batak languages',
    'Buginese',
    'Burmese',
    'Caucasian languages',
    'Cebuano',
    'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
    'Chuvash',
    'Divehi; Dhivehi; Maldivian',
    'Dogri',
    'Dravidian languages',
    'Egyptian (Ancient)',
    'Esperanto',
    'Finno-Ugrian languages',
    'French, Middle (ca.1400-1600)',
    'French, Old (842-ca.1400)',
    'Western Frisian',
    'Fulah',
    'Gayo',
    'Geez',
    'Irish',
    'German, Middle High (ca.1050-1500)',
    'German, Old High (ca.750-1050)',
    'Greek, Ancient (to 1453)',
    'Gujarati',
    'Hausa',
    'Himachali languages; Western Pahari languages',
    'Indic languages',
    'Judeo-Persian',
    'Judeo-Arabic',
    'Kashmiri',
    'Kawi',
    'Kazakh',
    'Khasi',
    'Central Khmer',
    'Kinyarwanda',
    'Konkani',
    'Komi',
    'Kurukh',
    'Kumyk',
    'Kurdish',
    'Ladino',
    'Lahnda',
    'Lao',
    'Limburgan; Limburger; Limburgish',
    'Ganda',
    'Lushai',
    'Madurese',
    'Magahi',
    'Maithili',
    'Mandingo',
    'Austronesian languages',
    'Minangkabau',
    'Uncoded languages',
    'Malagasy',
    'Munda languages',
    'Marwari',
    'Mayan languagesMayan languages',
    'Ndebele, North; North Ndebele',
    'Low German; Low Saxon; German, Low; Saxon, Low',
    'Nepal Bhasa; Newari',
    'Niger-Kordofanian languages',
    'Pedi; Sepedi; Northern Sotho',
    'Chichewa; Chewa; Nyanja',
    'Oriya',
    'Turkish, Ottoman (1500-1928)',
    'Papuan languages',
    'Pahlavi',
    'Panjabi; Punjabi',
    'Philippine languages',
    'Pali',
    'Prakrit languages',
    'Provençal, Old (to 1500); Occitan, Old (to 1500)',
    'Pushto; Pashto',
    'Quechua',
    'Rajasthani',
    'Romance languages',
    'Romany',
    'Yakut',
    'Sasak',
    'Sinhala; Sinhalese',
    'Sino-Tibetan languages',
    'Shona',
    'Sindhi',
    'Sotho, Southern',
    'Sundanese',
    'Syriac',
    'Tatar',
    'Telugu',
    'Tajik',
    'Tagalog',
    'Tswana',
    'Tsonga',
    'Turkmen',
    'Altaic languages',
    'Uzbek',
    'Wolof',
    'Xhosa',
    'Yoruba',
    'Zulu',
    'Greek, Ancient to 1453',
    'Greek, Modern 1453-',
    'Bokmål, Norwegian; Norwegian Bokmål',
    'Spanish',
    'Galitian',
    'Basque',
    'Romanian',
    'Chipewyan; Dene Suline',
    'Nahuatl languages',
    'Interlingua',
    'Faroese',
    'Norwegian Nynorsk; Nynorsk, Norwegian',
    'Norse, Old',
    'Sign Languages',
    'Southern Sami',
    'Northern Sami',
    'Sami languages',
    'Lule Sami',
    'Tigrinya',
    'Uighur; Uyghur',
    'No linguistic content',
    'Chamorro',
    'Filipino; Pilipino',
    'Siouan languages',
    'No linguistic content; Not applicable',
    'Flemish',
    'Cree',
    'talian',
    'Chagatai',
    'Germanic languages',
    'Gorontalo',
    'Swiss German; Alemannic; Alsatian',
    'Karen languages',
    'Occitan (post 1500)',
    'Ossetian; Ossetic',
    'ProvenÃ§al, Old (to 1500);Occitan, Old (to 1500)',
    'Semitic languages',
    'Akan',
    'Bambara',
    'Bemba',
    'Cornish',
    'Creoles and pidgins',
    'Dakota',
    'Ga',
    'Hawaiian',
    'Herero',
    'Iban',
    'Kachin; Jingpho',
    'Kikuyu; Gikuyu',
    'Kirghiz; Kyrgyz',
    'Kuanyama; Kwanyama',
    'Lingala',
    'Lozi',
    'Luo (Kenya and Tanzania)',
    'Makasar',
    'Manipuri',
    'Mayan languages',
    'Navajo; Navaho',
    'Ndonga',
    'Nyankole',
    'Santali',
    'Scots',
    'Shan',
    'Tetum',
    'Tigre',
    'Twi',
    'Sorbian languages',
    'latin',
    'Portugese',
    'Ukrainian',
    'Rundi'
];

function mapStateToProps(state) {
    const { hasChanged, language } = state.limiters.toJS();
    return {
        choices: languages,
        label: 'Langue',
        limiter: 'language',
        hasChanged,
        value: language
    };
}

function mapDispatchToProps(dispatch) {
    return bindActionCreators({
        onChange: actions.changeLimiter,
        onLimit: actions.limitSearch
    }, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(SelectLimiter);
